
libdsimmodels_la_SOURCES += d-flipflop-jk/d-flipflop-jk.c \
                    d-flipflop-jk/dflipflopjkcreate.c \
                    d-flipflop-jk/dflipflopjkinit.c \
                    d-flipflop-jk/dflipflopjkevent.c \
                    d-flipflop-jk/dflipflopjkconfig.c
