
OBJS += capacitor/capacitor.c.o \
		capacitor/capacitorcreate.c.o \
		capacitor/capacitorinit.c.o \
		capacitor/capacitorstamp.c.o \
		capacitor/capacitorvchanged.c.o \
		capacitor/capacitorconfig.c.o \
		capacitor/capacitoruninit.c.o
