
libdsimmodels_la_SOURCES += d-demux/d-demux.c \
                    d-demux/ddemuxcreate.c \
                    d-demux/ddemuxinit.c \
                    d-demux/ddemuxevent.c \
                    d-demux/ddemuxconfig.c
