
libdsimmodels_la_SOURCES += adc/adc.c \
                    adc/adccreate.c \
                    adc/adcinit.c \
                    adc/adcstamp.c \
                    adc/adcvchanged.c \
                    adc/adcconfig.c \
                    adc/adcuninit.c
