
libdsimmodels_la_SOURCES += dev/dev.c \
		dev/adevcreate.c \
		dev/adevinit.cxx \
		dev/adevstamp.cxx \
		dev/adevvchanged.cxx \
		dev/adevconfig.c \
		dev/adevreset.cxx \
		dev/adevuninit.cxx \
		dev/ddevcreate.c \
		dev/ddevinit.cxx \
		dev/ddevstamp.cxx \
		dev/ddevevent.cxx \
		dev/ddevconfig.c \
		dev/ddevreset.cxx \
		dev/ddevuninit.cxx
