
libdsimmodels_la_SOURCES += d-drvsrc/d-drvsrc.c \
                    d-drvsrc/ddrvsrccreate.c \
                    d-drvsrc/ddrvsrcinit.c \
                    d-drvsrc/ddrvsrcevent.c \
                    d-drvsrc/ddrvsrcconfig.c \
                    d-drvsrc/ddrvsrcclock.c
