
libdsimmodels_la_SOURCES += d-mux/d-mux.c \
                    d-mux/dmuxcreate.c \
                    d-mux/dmuxinit.c \
                    d-mux/dmuxevent.c \
                    d-mux/dmuxconfig.c
