
OBJS += dev/dev.c.o \
		dev/adevcreate.c.o \
		dev/adevinit.cxx.o \
		dev/adevstamp.cxx.o \
		dev/adevvchanged.cxx.o \
		dev/adevconfig.c.o \
		dev/adevreset.cxx.o \
		dev/adevuninit.cxx.o \
		dev/ddevcreate.c.o \
		dev/ddevinit.cxx.o \
		dev/ddevstamp.cxx.o \
		dev/ddevevent.cxx.o \
		dev/ddevconfig.c.o \
		dev/ddevreset.cxx.o \
		dev/ddevuninit.cxx.o
