
libdsimmodels_la_SOURCES += inductor/inductor.c \
		inductor/inductorcreate.c \
		inductor/inductorinit.c \
		inductor/inductorstamp.c \
		inductor/inductorvchanged.c \
		inductor/inductorconfig.c \
		inductor/inductoruninit.c
