
OBJS += inductor/inductor.c.o \
		inductor/inductorcreate.c.o \
		inductor/inductorinit.c.o \
		inductor/inductorstamp.c.o \
		inductor/inductorvchanged.c.o \
		inductor/inductorconfig.c.o \
		inductor/inductoruninit.c.o
