libdsimmodels_la_SOURCES += capacitor/capacitor.c \
                    capacitor/capacitorcreate.c \
                    capacitor/capacitorinit.c \
                    capacitor/capacitorstamp.c \
                    capacitor/capacitorvchanged.c \
                    capacitor/capacitorconfig.c \
                    capacitor/capacitoruninit.c
