
libdsimmodels_la_SOURCES += bjt/bjt.c \
                    bjt/bjtcreate.c \
                    bjt/bjtinit.c \
                    bjt/bjtstamp.c \
                    bjt/bjtvchanged.c \
                    bjt/bjtconfig.c \
                    bjt/bjtuninit.c
