
libdsimmodels_la_SOURCES += d-flipflop-delay/d-flipflop-delay.c \
                    d-flipflop-delay/dflipflopdelaycreate.c \
                    d-flipflop-delay/dflipflopdelayinit.c \
                    d-flipflop-delay/dflipflopdelayevent.c \
                    d-flipflop-delay/dflipflopdelayconfig.c
