
OBJS += mosfet/mosfet.c.o \
		mosfet/mosfetcreate.c.o \
		mosfet/mosfetinit.c.o \
		mosfet/mosfetstamp.c.o \
		mosfet/mosfetvchanged.c.o \
		mosfet/mosfetconfig.c.o \
		mosfet/mosfetuninit.c.o
