
libdsimmodels_la_SOURCES += d-buff/d-buff.c \
                    d-buff/dbuffcreate.c \
                    d-buff/dbuffinit.c \
                    d-buff/dbuffevent.c \
                    d-buff/dbuffconfig.c \
                    d-buff/dbuffuninit.c
