
OBJS += vsource/vsource.c.o \
		vsource/vsourcecreate.c.o \
		vsource/vsourceinit.c.o \
		vsource/vsourcestamp.c.o \
		vsource/vsourceconfig.c.o \
		vsource/vsourceuninit.c.o \
		vsource/vsourcemisc.c.o
