
libdsimmodels_la_SOURCES += d-lcd8544/d-lcd8544.c \
                    d-lcd8544/dlcd8544create.c \
                    d-lcd8544/dlcd8544init.c \
                    d-lcd8544/dlcd8544event.c \
                    d-lcd8544/dlcd8544config.c \
                    d-lcd8544/dlcd8544uninit.c \
					d-lcd8544/dlcd8544reset.c
	
