
libdsimmodels_la_SOURCES += logicstate/logicstate.c \
                    logicstate/logicstatecreate.c \
                    logicstate/logicstateinit.c \
                    logicstate/logicstateevent.c \
                    logicstate/logicstateconfig.c \
                    logicstate/logicstateuninit.c
