
libdsimmodels_la_SOURCES += mosfet/mosfet.c \
		mosfet/mosfetcreate.c \
		mosfet/mosfetinit.c \
		mosfet/mosfetstamp.c \
		mosfet/mosfetvchanged.c \
		mosfet/mosfetconfig.c \
		mosfet/mosfetuninit.c
