.PHONY: all clean subs subs_clean

SUB_DEPTH = ./..

include $(SUB_DEPTH)/autoconf.mk

CFLAGS += -Wno-unused-function -Wno-unused-but-set-variable
CXXFLAGS += -Wno-unused-function -Wno-unused-but-set-variable

#########################################################################
# Targets.

TARGET = libopendsim.$(.LIB)

OBJS += util/logtrace.c.o \
		util/string.c.o \
		util/sys-memory.c.o \
		util/sys-memory.cxx.o \
		util/hashmap.c.o \
		util/list.c.o \
		util/rbtree.c.o \
		util/prime.c.o \
		util/bound.c.o \

OBJS += scheme-intr/lisp-buffer.c.o \
		scheme-intr/lisp-fault.c.o \
		scheme-intr/lisp-lexer.c.o \
		scheme-intr/lisp-parser.c.o \
		scheme-intr/lisp.c.o

OBJS += math/circ-matrix/circmatrix.c.o \

OBJS += circuit/circuit.c.o \
		circuit/circ-pin.c.o \
		circuit/circ-node.c.o \
		circuit/circ-element.c.o \

#########################################################################
# Building rules.

include $(SUB_DEPTH)/build-aux/rules.generic.mk
include $(SUB_DEPTH)/build-aux/rules.end.mk

all: subs $(TARGET)
clean: subs_clean

$(TARGET): $(OBJS)

subs:
	$(MAKE) -C models all
	$(MAKE) -C devices all
	
subs_clean:
	$(MAKE) -C models clean
	$(MAKE) -C devices clean
