
libdsimmodels_la_SOURCES += register/register.c \
		register/registercreate.c \
		register/registerinit.c \
		register/registerstamp.c \
		register/registerconfig.c \
		register/registeruninit.c
