
libdsimmodels_la_SOURCES += vsource/vsource.c \
		vsource/vsourcecreate.c \
		vsource/vsourceinit.c \
		vsource/vsourcestamp.c \
		vsource/vsourceconfig.c \
		vsource/vsourceuninit.c \
		vsource/vsourcemisc.c
